#!/bin/bash
# Script to open all NCERT Geography books from VI to XII.
# To open the folder of class VI, type 'Geography 6' similarly for others.
# Written by: Himanshu Shekhar

if [ "$1" == "6" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VI/Geography/
elif [ "$1" == "7" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VII/Geography/
elif [ "$1" == "8" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VIII/Geography/
elif [ "$1" == "9" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/IX/Geography/
elif [ "$1" == "10" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/X/Geography/
elif [ "$1" == "11" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/XI/Geography/
elif [ "$1" == "12" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/XII/Geography/
else
  echo "Enter Arguments between 6 to 12"
fi


