#!/bin/bash
# Script to open all NCERT History books from VI to XII.
# To open the folder of class VI, type 'history 6' similarly for others.
# Written by: Himanshu Shekhar

if [ "$1" == "6" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VI/History/
elif [ "$1" == "7" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VII/History/
elif [ "$1" == "8" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/VIII/History/
elif [ "$1" == "9" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/IX/History/
elif [ "$1" == "10" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/X/History/
elif [ "$1" == "11" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/XI/History/
elif [ "$1" == "12" ]
then
  /usr/bin/gnome-open ~/Downloads/NCERT\ books/ncert/XII/History/
else
  echo "Enter Arguments between 6 to 12"
fi


