#!/usr/bin/env python3
# Implementing Quick Sort
#

from random import randint

def quickSort(array):
    if len(array) < 2:
        return array

    low, same, high = [], [], []
    pivot = array[randint(0, len(array) - 1)]

    for item in array:
        if item < pivot:
            low.append(item)
        elif item == pivot:
            same.append(item)
        elif item > pivot:
            high.append(item)

    return quickSort(low) + same + quickSort(high)




